---
title: "AWS-study-01"
description: |
  AWSの勉強-AWS認定試験について
author:
  - name: あんごう
    url: about.html
date: "`r format(Sys.time(), '%Y/%m/%d')`"
categories:
  - AWS
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
    toc_float: true
draft: true
---

今回から、AWSのソリューションアーキテクトをとるための勉強の備忘録を残そうと思います。
勉強する本については、[これ](https://www.amazon.co.jp/AWS%E8%AA%8D%E5%AE%9A%E3%82%A2%E3%82%BD%E3%82%B7%E3%82%A8%E3%82%A4%E3%83%883%E8%B3%87%E6%A0%BC%E5%AF%BE%E7%AD%96-%E3%82%BD%E3%83%AA%E3%83%A5%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%A2%E3%83%BC%E3%82%AD%E3%83%86%E3%82%AF%E3%83%88%E3%80%81%E3%83%87%E3%83%99%E3%83%AD%E3%83%83%E3%83%91%E3%83%BC%E3%80%81SysOps%E3%82%A2%E3%83%89%E3%83%9F%E3%83%8B%E3%82%B9%E3%83%88%E3%83%AC%E3%83%BC%E3%82%BF%E3%83%BC-%E5%B9%B3%E5%B1%B1-%E6%AF%85/dp/4865941991/ref=sr_1_8?__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&crid=2EDNKTY35ZXG5&dchild=1&keywords=%E3%82%BD%E3%83%AA%E3%83%A5%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%A2%E3%83%BC%E3%82%AD%E3%83%86%E3%82%AF%E3%83%88&qid=1624116544&s=books&sprefix=%E3%82%BD%E3%83%AA%E3%83%A5%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%2Cstripbooks%2C341&sr=1-8)を読んでいきたいと思います。

# ソリューションアーキテクトについて

**<u>設計能力</u>を問うソリューションアーキテクトの合格**

## 1.1 試験の概要

特にまとめることがないので、スキップ

## 1.2 AWSサービスのカテゴリ分類と対応試験

### AWSサービスのカテゴリ分類

図があるが、著作権上問題になるのでスキップする

## 1.3 AWS認定試験の体系とその特徴

- 設計能力を問うソリューションアーキテクト
- 開発能力を問うデベロッパー
- 運用能力を問うSysOpsアドミニストレーター

- AWSが提供するサービスそのものをしっかり理解することが重要
- アソシエイトレベルの試験は、それぞれ1年程度のAWS経験が必要とされる難易度であると定義されており、合格するためにはAWS固有のサービス機能の基本を正確に理解する

### AWS 認定ソリューションアーキテクト - アソシエイトの特徴

- AWSを使った基本設計やアーキテクチャにおける基礎知識を確認する試験
- 幅広い分野から出題されること
- AWS Well-Architected フレームワークに沿ったクラウド標準設計

AWS Well-Architectedフレームワークとは?

- AWSは完全にセルフサービスであり、開発者にとって制約が少なく、自由かつ簡単にサービスを組み合わせて開発できるのが特徴
- 業務サービスの本番稼働を目的として利用されるようになると、開発者側の自由な設計が災いして、AWSサービスに障害等が発生して本番サービスに影響が出たり、性能・コスト・セキュリティ・運用の面で、自由な設計に起因して課題も出てくるようになりました
- そこで、AWS固有の設計ノウハウを一般化して普及させる機運が高まり、さまざまな業界のAWSのソリューションアーキテクト(AWS上でのシステム構成とAWS内部構造の両面を把握している技術者)が、自らのノウハウやベストプラクティスをリファレンスとして公開しました。それを標準化したものである。

- AWS Well-Architectedフレームワークは「オペレーショナルエクセレンス」「セキュリティ」「信頼性」「パフォーマンス効率」「コスト最適化」の5つで構成されている。

AWS認定ソリューションアーキテクト - アソシエイトで最も多く出題される範囲が

- 高い回復性
- パフォーマンス
- セキュアアプリケーション

の3つである。

- 高い回復性は、Multi-AZを中心にしたSLA^[SLAとは、Service Level Agreementの略で、サービスを提供事業者とその利用者の間で結ばれるサービスのレベル（定義、範囲、内容、達成目標等）に関する合意サービス水準、サービス品質保証などと訳されます。これは、サービスを提供する事業者が契約者に対して、どの程度まで品質を保証できるかを明示したものです。]を意識しつつ、ELBやRDSを中心にWeb層とDB層の可用性を以下に保つかを問われる。
- AWSならではの豊富なコンピューティングリソースを活かして、どのようにスケールアウトやスケールアップをさせるかが問われる。
- AWSのようなパブリッククラウドならではの責任分界点や認証などを第9章のIAM(Identity and Access Management)を中心に活用し、セキュアアプリケーションをどのように構成するかが問われる。

## 1.4 AWSを理解するには

### S3とEC2から理解する

- S3を基盤にしたサービスは、SQS・SNS・DynamoDBなどである。
- EC2を基盤にしたサービスは、RDSやELBなどである。

上記2つがほぼ基盤なので、そこから理解することが望ましい

メモ: IPアドレッシングとはネットワーク上の機器にIPアドレスを割り振ることです。

### VPCを理解する

- VPCはSDN(Software Defined Network)^[[SDNとは](https://www.nic.ad.jp/ja/basics/terms/sdn.html)]であり、慣れていないと少し戶惑います。

> Amazon Virtual Private Cloud (Amazon VPC) は、定義した論理的に分離された仮想ネットワークで AWS リソースを起動できるようにするサービスです。独自の IP アドレスの範囲の選択、サブネットの作成、ルートテーブルやネットワークゲートウェイの設定など、仮想ネットワーク環境を完全に制御できます。仮想プライベートクラウド内のほとんどのリソースに IPv4 と IPv6 の両方を使用できるため、リソースとアプリケーションへの安全で簡単なアクセスが保証されます。

### リソース指向でIAM と CloudFormation を理解する

- リソースとは、EC2の仮想インスタンスなどのクラウドサービスの対象のこと
- リソース指向とは、この対象を中心にポリシー制御を考えることを指す。
<aside>
ポリシー制御とは、アプリケーションの適切な使用とパフォーマンスの確保、お客様の環境にに対する脅威を阻止するための次世代セキュリティ プラットフォームのアクションを表しています。
</aside>

- IAMユーザーの考え方は一般的で、IAMユーザーにアクセス制御を加えること
- EC2であればIAMロールでアクセス制御を加える
- S3であればバケットポリシーでアクセス制御を加える

- CloudFormationは、リソース情報をテンプレートとしてJSON形式でまとめたものである。


### Route 53 を使って DNS を理解する

- AWSのサービスには、IPアドレスではなくAmazonが提供するFQDN(Fully Qualified Domain Name)でアクセスする、という特徴があります。
- WebアクセスにFQDNが用いられているのと同様に、スケールさせたりアプリケーションリリースを切り替えたりするのに、DNS^[[DNSとは?](https://www.nic.ad.jp/ja/basics/beginners/dns.html)]が有効な手法だから
- AWSの環境に移行すると、DNSをベースにしたアーキテクチャを考慮する必要があり、AWSが提供しているDNSサービスであるRoute 53を活用していくことになります。
> Route 53は、パブリックIPだけでなくVPC内のプライベートIPにも対応しています。また、IPv4とFQDNをマッピングするAレコードだけでなく、別名を付与するCNAMEレコード、IPv6に対応するためのAAAAレコード、ヘルスチェックをベースにした負荷分散やフェイルオーバーにも非常に有用です。

参考サイト

- [AWS Kinesis](https://aws.amazon.com/jp/kinesis/)
- [OSSとは](https://hnavi.co.jp/knowledge/blog/oss/)
- [HA構成とは?](https://bcblog.sios.jp/what-is-ha-failover-loadbalancing/#:~:text=HA%E6%A7%8B%E6%88%90%E3%81%A8%E3%81%AF%E3%80%81%E5%8F%AF%E7%94%A8%E6%80%A7,%E3%81%A8%E3%81%84%E3%81%86%E6%84%8F%E5%91%B3%E3%81%AB%E3%81%AA%E3%82%8A%E3%81%BE%E3%81%99%E3%80%82)
- [DBA 【Database Administrator】とは](https://e-words.jp/w/DBA.html)
- [エンドポイント 【endpoint】 end pointとは](https://e-words.jp/w/%E3%82%A8%E3%83%B3%E3%83%89%E3%83%9D%E3%82%A4%E3%83%B3%E3%83%88.html#:~:text=%E3%82%A8%E3%83%B3%E3%83%89%E3%83%9D%E3%82%A4%E3%83%B3%E3%83%88%E3%81%A8%E3%81%AF%E3%80%81%E7%AB%AF%E7%82%B9,%E3%82%92%E6%8C%87%E3%81%99%E3%81%93%E3%81%A8%E3%81%8C%E5%A4%9A%E3%81%84%E3%80%82)

- [CI/CDとは何か?](https://codezine.jp/article/detail/11083)

## 1.5 元 AWS アーキテクト・コンサルタントの視点からのエンジニア育成

とくにコメントがないので、スキップ

## 1.6 AWSグローバルプレミアムパートナーから見た合格の秘訣

ハンズオンの経験が少ないと不合格になる可能性がある。

## 1.7 試験のアップデートで出題が強化されたサービス

詳細なことはこの後の章で述べるので、スキップ

# まとめ

## この章を読んだ感想

ソリューションアーキテクトに求められる要件を覚えること
