---
title: "aws-study-03"
description: |
  AWSの勉強-コンピューティング
author:
  - name: あんごう
    url: about.html
date: "`r format(Sys.time(), '%Y/%m/%d')`"
categories:
  - AWS
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
    toc_float: true
draft: true
---

# 3. コンピューティング

## 3.1 EC2とは

EC2起動のために必要な起動設定

[](./3.1.png)

用語の解説サイト

[ソフトウェアライセンス](https://wa3.i-3-i.info/word16282.html)
[BYOL (Bring Your Own License)](https://e-words.jp/w/BYOL.html)


## 3.2 EC2のストレージ

EC2の起動に関わるストレージ関連の重要ポイントとして、以下の3つの用語について説明

### AMI (Amazon Machine Images)

- AWSが提供するOSのテンプレートイメージ
- 変更を加えた状態のインスタンスから、自分専用のAMIを**カスタムAMI**として作成することができる。
- カスタムAMIは、リージョン内のどのアベイラビリティーゾーンでも利用できるが、リージョンをまたぐ場合は、別のリージョンでコピーを作成しないと行けない。

### EBS(Elastic Block Store)ボリューム

- EC2に仮想的に外付け(アタッチ)される、ブロックレベルのストレージサービス
- OSが起動するためのブート領域や、アプリケーションが処理を行うデータ、処理結果を記録したログなどを保存するストレージ領域
- **利用者がEC2を停止(Stop)したとしても、明示的にEBSボリュームを削除しない限りデータは保持される**
- EBSボリュームは、アベイラビリティーゾーン単位で作成される。
- EBSボリュームは、異なるアベイラビリティーゾーンから利用することはできない。
- 複数のEC2のインスタンスから、単一のEBSボリュームをアタッチして共有ストレージのように利用することはできない。

[EBSボリュームを別のAZで使用するための手順](./3.2.png)

[IOPSとは](https://www.storage-channel.jp/blog/iops.html#toc-1)

[EBSのボリュームタイプごとの特徴](./3.3.png)
[スループットとは](https://e-words.jp/w/%E3%82%B9%E3%83%AB%E3%83%BC%E3%83%97%E3%83%83%E3%83%88.html#:~:text=%E3%82%B9%E3%83%AB%E3%83%BC%E3%83%97%E3%83%83%E3%83%88%E3%81%A8%E3%81%AF%E3%80%81%E6%A9%9F%E5%99%A8%E3%82%84,%E6%84%8F%E5%91%B3%E3%81%99%E3%82%8B%E3%81%93%E3%81%A8%E3%81%8C%E5%A4%9A%E3%81%84%E3%80%82)

[ワークロードとは](https://e-words.jp/w/%E3%83%AF%E3%83%BC%E3%82%AF%E3%83%AD%E3%83%BC%E3%83%89.html#:~:text=%E3%83%AF%E3%83%BC%E3%82%AF%E3%83%AD%E3%83%BC%E3%83%89%E3%81%A8%E3%81%AF%E3%80%81%E4%BB%95%E4%BA%8B,%E6%84%8F%E5%91%B3%E3%82%92%E6%8C%81%E3%81%A4%E8%8B%B1%E5%8D%98%E8%AA%9E%E3%80%82)

[通常インスタンスとEBS最適化インスタンスの違い](./3.4.ppng)

### EBSスナップショット

- EBSのバックアップに当たるもの
- S3上に作成され、AMIと同様に、別リージョンにもコピーすることが可能

### インスタンスストア

- EC2サーバーに内蔵されたローカルディスクのこと
- 揮発性という特徴がある
- 揮発性とは、インスタンスが停止 or 削除されると、インスタンスストア上のデータが失われること。

- EBSボリュームはアベイラビリティーゾーン単位で作成される。



## 3.3 EC2のネットワーク

- AWS上で利用できるIPアドレスは以下の3つ

[AWS上のIPアドレスの種類と特徴](3.5.png)

[プライベートIPアドレスとは](https://www.atmarkit.co.jp/aig/06network/privateip.html)

- ENI
  - 物理サーバーで例えると[NIC(Network Interface Card)](https://e-words.jp/w/NIC.html)に該当
  - EC2のインスタンスは1つ以上のENIを持っており、複数のIPアドレスが割り当てられる。

- プレイスメントグループ
  - EC2インスンタンス起動時に、オプションとしてプレイスメントグループを指定することが可能
  - 同じプレイスメントグループに所属するEC2インスタンス同士が広帯域のネットワークで接続され、高いネットワークパフォーマンスを実現することが可能
  - これにより、たくさんのサーバーを連結して処理を行うHPC(ハイパフォーマンスコンピューティング)やビッグデータの分散処理を行うことが可能になる。
  - グループに所属するEC2インスタンスは同一のアベイラビティゾーン上で起動する必要がある。


## 3.4 ECのセキュリティ

1. タイプ(TCP、UDP、ICMP、特定のサービスポートなど)
2. プロトコル(タイプに応じた内容が自動的に選択される。カスタムプロトコルの場合は入力する)
3. ポート範囲(タイプに応じた内容が自動的に選択される。カスタムプロトコルの場合は入力する)
4. ソース(「カスタム」、「任意の場所」、「マイIP」から選択する)
5.説明(ポリシーの設定内容の概要や設定意図などを記載する)

セキュリティグループのデフォルト設定では、EC2インスタンスに対するインバウンドの通信(インスタンスに向かってくる通信)は、すべて拒否される

## 3.5 EC2の運用管理

### EC2のライフサイクル

EC2のインスタンスはAMIから起動(Start)し、不要になった場合は削除(Terminate)します。この起動から削除までの一連の流れを、EC2のライフサイクルと呼びます。

[インスタンスへの操作内容による挙動の違い](./3.6.png)

- Stop状態とStop-Hibernate状態の違いはOSのメモリ上のデータが削除されるかされないかの違いである。

インスタンスメタデータ: 当該インスタンス固有のデータのこと
- ホスト名、IPアドレス、インスタンスIDなどが含まれる。
- 運用処理を自動化することも可能

ユーザーデータ
- インスタンスが起動したタイミングで必要なOS設定やソフトウェアのインストールを自動実行することができるようにするためのスクリプト

## 3.6 チュートリアル
